language: go
go:
    - 1.3

cache:
    directories:
    - $HOME/gopath/src/github.com/mozilla-services/pushgo/go
    - $HOME/gopath/src/github.com/mozilla-services/pushgo/libmemcached-1.0.18

install:
    - make memcached
    - make

script:
    - make simplepush
